### ISSUE TITLE
Pod Disruption Budget round off of maxUnavailable

### ISSUE THREAD

**Issue by pranay142** [kubernetes/apimachinery#100]
Kubernetes documentation for Pod disruption budget when specified in percentage is expected to rounds up to the nearest integer.
However the round off is being done to the upper limit and not to the nearest integer.
For example with total number of pods as 3 and maxUnavailable set to 40%(1.2 Pods), the nearest integer is 1 however it is being set as 2.

Max unavailable:  40%
Selector:         app=web-app
Status:
    Allowed disruptions:  2
    Current:              3
    Desired:              1
    Total:                3

The below code always provide the ceil value and hence provides the higher number.

https://github.com/kubernetes/apimachinery/blob/master/pkg/util/intstr/intstr.go#L138

**Comment by liggitt** [comment]
Thanks for the issue. This should be filed against https://github.com/kubernetes/kubernetes/ and tagged with `/sig apps scheduling`

Can you include the reference to the documentation you mentioned that describes how the maxUnavailable value treats partial values as well?
