### ISSUE TITLE
[Question] How to decode a RawExtension ?

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/apimachinery#102]
I have a hard time understanding how decoding a  `RawExtension` into an `Object`.

Given the comment below:

https://github.com/kubernetes/apimachinery/blob/829ed199f4e0454344a5bc5ef7859a01ef9b8e22/pkg/runtime/types.go#L49-L102

Especially this part:

>  // The next step is to copy (using pkg/conversion) into the internal struct. The runtime 
 > // package's DefaultScheme has conversion functions installed which will unpack the 
 > // JSON stored in RawExtension, turning it into the correct object type, and storing it 
 > // in the Object.

I fail to find anything useful in `pkg/conversion` that could help me in converting the `RawExtension` into an `Object`. All i can think of is something like this:

```
codecs := serializer.NewCodecFactory(scheme)
deserializer := codecs.UniversalDeserializer()
obj, gvk, err := deserializer.Decode(rawExtension.Raw, nil, nil)
```

Has someone any advice on the correct approach to use here ?

**Comment by dionysius** [comment]
I've stumbled on this issue as well and tried to look a bit around. I found out that [this project](https://github.com/searchlight/grafana-operator) is using RawExtension with the help of [this issue](https://github.com/kubernetes/kubernetes/issues/88252) (while the issue itself is not directly related to RawExtension itself, but was helpful to dig trough the source code)

- Review the definition of the type using RawExtension: in go https://github.com/searchlight/grafana-operator/blob/7e1d1eecd3c583ff9800f5726b31da64f0641a5d/apis/grafana/v1alpha1/dashboard_types.go#L49, in proto https://github.com/searchlight/grafana-operator/blob/7e1d1eecd3c583ff9800f5726b31da64f0641a5d/apis/grafana/v1alpha1/generated.proto
- Use of `+kubebuilder:pruning:PreserveUnknownFields` is important, respectively your CRD needs the option `x-kubernetes-preserve-unknown-fields: true` if you use CRD v1 (also for v1alpha1 if you enabled pruning of additional fields)
- They write the raw json directly to `*RawExtension.Raw`: https://github.com/searchlight/grafana-operator/blob/7e1d1eecd3c583ff9800f5726b31da64f0641a5d/test/e2e/dashboard_test.go#L122.
- That means you are free to use the `.Raw` field for reading and writing, as long as it is a json (! - yaml didn't work for me) encoded blob as `[]byte` in the end, you can do whatever you want outside of it.
- Also neat: kubectl is still able to display that field in yaml with the correct indention and that resource is also editable in that form.

I just can't say if this is the right official way, but I hope I could help you.

**Comment by hicaistar** [comment]
I've found that kube-scheduler use RawExtension for PluginConfig: https://github.com/kubernetes/kube-scheduler/blob/master/config/v1beta1/types.go#L225, and it use DecodeNestedObjects interface which I'm not familiar with. When kube-scheduler start, it will read a json file, code is here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/configfile.go#L40 ， it also use 
```serializer.NewCodecFactory(scheme)```.

**Comment by Dhua-v** [comment]
Kubernetes admission review also uses the type { Raw []byte 'json:"-"`,Object Object `json:"-"` }

Which A.T. golang official doc, will just ignore the Raw and Object fields during unmarshal (beacause of a hyphon in the tag), inspite of populating them. Cant understand why during unmarshal, "Raw" field is populated.
