### ISSUE TITLE
Marshal writes CreationTimestamp: null

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/apimachinery#119]
Marshal writes `CreationTimestamp: null` by default, which is unintuitive, undesirable, and probably unnecessary.

```
type Resource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
}

func main() {
	cm := &Resource{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ConfigMap",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "name",
			Namespace: "namespace",
		},
	}

	cmBytes, err := yaml.Marshal(cm)
	if err != nil {
		return nil, err
	}

	fmt.Println(string(cm))
}
```

Prints:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: name
  namespace: namespace
  creationTimestamp: null
```

It looks like this behavior might have been intentional:
https://github.com/kubernetes/apimachinery/commit/6556ef5891e14b543b3e255048a7647e70785f7f

But it's not clear why ObjectMeta doesn't just use a pointer `*Time` instead of a raw `Time` object, like DeletionTimestamp does. at least that way the default would be nil and the yaml.Marshal would omit it.

**Comment by karlkfi** [comment]
Original upstream PR: https://github.com/kubernetes/kubernetes/pull/53464

**Comment by liggitt** [comment]
seems like a duplicate of https://github.com/kubernetes/kubernetes/issues/67610

**Comment by lavalamp** [comment]
Yup, will close in favor of that.

Also see this for how the `null` ends up getting emitted: https://github.com/kubernetes/apimachinery/blob/57f2a0733447cfd41294477d833cce6580faaca3/pkg/apis/meta/v1/time.go#L142-L145
