### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by fgrosse** [kubernetes/apimachinery#121]
Hey there, I was following [a tutorial][1] and tried to fetch the current version of `k8s.io/apimachinery` which currently results in the error below.

```
$ go get -u k8s.io/apimachinery/...
# k8s.io/apimachinery/pkg/util/strategicpatch/testing
/home/fgrosse/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/strategicpatch/testing/openapi.go:60:45: cannot use info (type "gopkg.in/yaml.v2".MapSlice) as type *"gopkg.in/yaml.v3".Node in argument to openapi_v2.NewDocument
/home/fgrosse/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/util/strategicpatch/testing/openapi.go:60:71: not enough arguments in call to compiler.NewContext
	have (string, nil)
	want (string, *"gopkg.in/yaml.v3".Node, *compiler.Context)
```

[1]: https://cuetorials.com/first-steps/import-configuration/#Importing_Go_to_Cue

**Comment by liggitt** [comment]
what version of go are you using?

**Comment by fgrosse** [comment]
Hey @liggitt , this is my Go version:

```
$ go version                       
go version go1.16.3 linux/amd64
```

**Comment by nikhita** [comment]
@fgrosse I wonder if this is expected because `go get -u` will also update dependencies of the package mentioned on the command line:

From https://golang.org/cmd/go/#hdr-Add_dependencies_to_current_module_and_install_them:

```
The -u flag instructs get to update modules providing dependencies of packages named on the command line to use newer minor or patch releases when available.
```

If you do a `go get k8s.io/apimachinery/...`, it will fetch the latest apimachinery and not thrown an error.

**Comment by fgrosse** [comment]
Excellent point about the update flag. Seems I need to read a bit more about it and maybe open an issue at the tutorial I was following but this ticket can then be closed.

Thanks for looking into it 🙂

**Comment by nikhita** [comment]
Closing :)
