### ISSUE TITLE
Go 1.17 compatibility issue: TestIsValidIP and TestIsValidIPv4Address failure

### ISSUE THREAD

**Issue by eclipseo** [kubernetes/apimachinery#128]
Due to https://github.com/golang/go/commit/d3e3d03666bbd8784007bbb78a75864aac786967, both TestIsValidIP and TestIsValidIPv4Address fail with IP "1.1.1.01".

```
k8s.io/apimachinery/pkg/util/validation
--- FAIL: TestIsValidIP (0.00s)
    validation_test.go:340: expected true for "1.1.1.01": [must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff)]
--- FAIL: TestIsValidIPv4Address (0.00s)
    validation_test.go:368: expected "1.1.1.01" to be valid IPv4 address: [[]: Invalid value: "1.1.1.01": must be a valid IPv4 address]
FAIL
exit status 1
FAIL	k8s.io/apimachinery/pkg/util/validation	0.008s
```

I'm not sure what's the best course of action to patch this while keeping compatibility with Go < 1.17.

**Comment by liggitt** [comment]
WIP fix in https://github.com/kubernetes/kubernetes/pull/104368, expected to merge in O(days), will sync to k8s.io/apimachinery `master` branch and the v0.23.0-... pre-release tag cut after merge

**Comment by liggitt** [comment]
closing in favor of the canonical issue tracking this in https://github.com/kubernetes/kubernetes/issues/100895
