### ISSUE TITLE
metav1.Duration doesn't parse `d`, `w`; conflicts with kubebuilder `format=duration` validation

### ISSUE THREAD

**Issue by 2uasimojo** [kubernetes/apimachinery#131]
Despite validation of type=duration being [documented](https://github.com/kubernetes/apiextensions-apiserver/blob/29400d7010f44f7d6ad2c6762604185143382598/pkg/apis/apiextensions/v1/types_jsonschema.go#L51) as parsed by time.ParseDuration, which is [what the unmarshaller does](https://github.com/kubernetes/apimachinery/blob/df993592a122931b8aac4db57689e09458a2332c/pkg/apis/meta/v1/duration.go#L39), it is actually [parsed](https://github.com/kubernetes/apiextensions-apiserver/blob/29400d7010f44f7d6ad2c6762604185143382598/pkg/apiserver/schema/cel/values.go#L135) by strfmt.ParseDuration, which is more lenient in that it [accepts `d` (days) and `w` (weeks)](https://github.com/kubernetes/kube-openapi/blob/424119656bbfd8b633f4b9f9ef5f93cd1e01266a/pkg/validation/strfmt/duration.go#L51-L52).

The result is that the round trip is broken: go type => CRD => CR with `d` or `w` => apiserver validation (accepts `d`/`w`) => etcd => GET => unmarshal (blows up on `d`/`w`) => go type.

[Example](https://github.com/openshift/hive/blob/9c572408b5299c520160e7a317c52e80b0415b9f/apis/hive/v1/clusterclaim_types.go#L28-L30) of such a CRD struct field definition.

And a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2050332) that uncovered the problem.

cf. https://github.com/kubernetes/apiextensions-apiserver/issues/56

---

Possible solutions:
- Have metav1.Duration.UnmarshalJSON use (an equivalent of) strfmt.ParseDuration instead of time.ParseDuration. Note that the former is a [superset](https://github.com/kubernetes/kube-openapi/blob/424119656bbf/pkg/validation/strfmt/duration.go#L89-L91) of the latter -- i.e. this is guaranteed not to reject existing _working_ strings.
- Add a type to metav1 ("ScalaDuration"?) that uses the more lenient parser.

**Comment by CaptainIRS** [comment]
This is still an issue. It's easy for someone to set a field of type duration to something like "1d" and pass the validation successfully, but then the controller that uses the value crashes.

/remove-lifecycle stale
