### ISSUE TITLE
Indirect dependency golang.org/x/text v0.3.2 causing Blackduck vulnerability

### ISSUE THREAD

**Issue by praneeth100** [kubernetes/apimachinery#139]
Blackduck scan on 0.23.1 resulted in BD vulnerability due to indirect dependency of golang.org/x/text v0.3.2 
k8s.io/apimachinery v0.23.1 -> github.com/onsi/ginkgo v1.14.0 -> golang.org/x/text v0.3.2 

The same issue should be happening on latest k8s.io/apimachinery version v0.24.0 as it is pointing to github.com/onsi/ginkgo v1.14.0.

<img width="1623" alt="Screenshot 2022-05-12 at 3 11 05 PM" src="https://user-images.githubusercontent.com/104485499/168042331-f7826df0-94d5-429c-bffb-3fcad2c1d2ac.png">
<img width="1310" alt="Screenshot 2022-05-12 at 3 11 21 PM" src="https://user-images.githubusercontent.com/104485499/168042348-a9d267d5-0526-48ed-b872-3cdedbc062d8.png">

k8s.io/apimachinery dependent modules needs to be updated?
github.com/onsi/ginkgo v1.15.0 does not have golang.org/x/text v0.3.2  dependency.

**Comment by dims** [comment]
this was actually fixed :)

```
[dims@dims-m1-7728 07:48] ~/go/src/k8s.io/kubernetes ⟩ rg golang.org/x/text go.*
go.sum
447:golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
448:golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=

go.mod
237:	golang.org/x/text v0.3.7 // indirect
501:	golang.org/x/text => golang.org/x/text v0.3.7
```
