### ISSUE TITLE
Provide a multiplication method for the resource.Quantity

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes/apimachinery#150]
Currently, the resource package provides helper methods to calculate Quantity, such as `Add` and `Sub`:

https://github.com/kubernetes/apimachinery/blob/8d1258da8f386b809d312cdda316366d5612f54e/pkg/api/resource/quantity.go#L565-L567

https://github.com/kubernetes/apimachinery/blob/8d1258da8f386b809d312cdda316366d5612f54e/pkg/api/resource/quantity.go#L582-L584

Batch workloads often replicate the same PodTemplate, and controllers calculate the resources needed for all containers.

In that case, It is inconvenient to call the `Add` function as many times as podTemplate, so I would like to create a helper function for multiplication.

/cc @alculquicondor

**Comment by alculquicondor** [comment]
/close

please open in kubernetes/kubernetes
