### ISSUE TITLE
Bad deprecation notices in 0.27.1 ?! Referenced `PollWithContextTimeout` does not exist ?!

### ISSUE THREAD

**Issue by andreas-kupries** [kubernetes/apimachinery#153]
After a bump to 0.27.1 the golang-ci-linter told me

> wait.PollImmediate is deprecated: This method does not return errors from context, use PollWithContextTimeout

Looking at the 0.27.1 documentation I find `PollWithContext`, but no `PollWithContextTimeout`.

https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#PollWithContext
https://pkg.go.dev/search?q=PollWithContextTimeout&m=symbol

Grepping the package sources I find that `PollWithContextTimeout` is only referenced in the deprecation notices in the comments. No implementation is found. See below.

The nearest similar function looks to be https://pkg.go.dev/k8s.io/apimachinery/pkg/util/wait#PollUntilContextTimeout

> % grep -rn PollWithContextTimeout .
./k8s.io/apimachinery@v0.27.1/pkg/util/wait/poll.go:44:// inline usage. All other behavior is identical to PollWithContextTimeout.
./k8s.io/apimachinery@v0.27.1/pkg/util/wait/poll.go:62:// Deprecated: This method does not return errors from context, use PollWithContextTimeout.
./k8s.io/apimachinery@v0.27.1/pkg/util/wait/poll.go:81:// Deprecated: This method does not return errors from context, use PollWithContextTimeout.
./k8s.io/apimachinery@v0.27.1/pkg/util/wait/poll.go:153:// Deprecated: This method does not return errors from context, use PollWithContextTimeout.
./k8s.io/apimachinery@v0.27.1/pkg/util/wait/poll.go:171:// Deprecated: This method does not return errors from context, use PollWithContextTimeout.

What is the actual method to use instead of the deprecated ones ?

**Comment by damdo** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/117143/files
I think we can close this.

**Comment by iblancasa** [comment]
I can see this problem in `v0.27.3`:
```
SA1019: wait.Poll is deprecated: This method does not return errors from context, use PollWithContextTimeout. Note that the new method will no longer return ErrWaitTimeout and instead return errors defined by the context package. Will be removed in a future release.
```

**Comment by till** [comment]
WWIW, can also confirm on 0.27.5.

**Comment by till** [comment]
I understand that no one has time, but can no one look into this and see if this is a bug?

**Comment by kaovilai** [comment]
> can no one look

yep no one looked :)
