### ISSUE TITLE
Request to remove reference to deprecated module 'github.com/golang/protobuf'

### ISSUE THREAD

**Issue by abhithmv** [kubernetes/apimachinery#157]
Hi,
apimachinery has a reference to deprecated module 'github.com/golang/protobuf'. Because of which our consuming module depends indirectly on deprecated module.
Is it possible to remove the deprecated module and release a new version of apimachinery?
Thanks.

**Comment by dims** [comment]
sorry no. We've documented why we are still refer to it

https://cs.k8s.io/?q=github.com%2Fgolang%2Fprotobuf&i=nope&files=staging%2F.*%5C.go&excludeFiles=&repos=kubernetes/kubernetes

/close
