### ISSUE TITLE
ParseGroupKind parses back to front

### ISSUE THREAD

**Issue by polyrain** [kubernetes/apimachinery#158]
The method `ParseGroupKind` [found here](https://github.com/kubernetes/apimachinery/blob/v0.27.2/pkg/runtime/schema/group_version.go#L76) reads as if the string you pass in should be ordered as `"Group.Kind"` (and the argument name similarly implies this). However, the actual parsing of the string switches the order, instead returning a `GroupKind` struct with the first half of the string stored as the `Kind` and the second half stored as the `Group`. 

This is to say, the string `apps.Deployment` will be parsed as `GroupKind{group: Deployment, kind: apps}` which is incorrect.

Here's an example using the Go playground: https://go.dev/play/p/G1L4qJwGzru

**Comment by tamilselvan1102** [comment]
The input parameter is in the format of either **`Kind.group.com` or `Kind.version.group.com`**.
so ParseGroupKind() method logic is correct.
Ref:  https://github.com/kubernetes/apimachinery/blob/v0.27.2/pkg/runtime/schema/group_version.go#L43

**Comment by polyrain** [comment]
Ah, I was thrown off by the name and didn't realise the convention was to have them in that order. Thanks for clarifying!
