### ISSUE TITLE
(*IntOrString) IntValue() always returns zero when IntOrString is a percentage

### ISSUE THREAD

**Issue by kargakis** [kubernetes/apimachinery#16]
https://github.com/kubernetes/apimachinery/blob/21807b270ec15d19215659a5caa08b17f66d6f44/pkg/util/intstr/intstr.go#L104-L107
https://play.golang.org/p/YQMgFOpopM

There is no added value by that conversion, even worse it can be misused.

@kubernetes/sig-api-machinery-bugs

**Comment by deads2k** [comment]
@kargakis can you open against k8s.io/kubernetes and we'll get it assigned?

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/issues/49487
