### ISSUE TITLE
Compare group, kind and name instead of just UIDs when checking controller ref

### ISSUE THREAD

**Issue by therealak12** [kubernetes/apimachinery#160]
There's a method called `IsControlledBy` defined [here](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/controller_ref.go#L24). It compares the UID of the controller reference with the UID of the target object. As [pointed out by Vince Prignano](https://github.com/kubernetes-sigs/controller-runtime/issues/2380#issuecomment-1638475697) comparing UIDs won't work if the owner is recreated for example. Comparing group, kind, and name would be better here.

**Comment by vincepri** [comment]
I don't think the function here can be changed lightly or at all actually. The controller runtime definition is more broad and was introduced a few years ago in https://github.com/kubernetes-sigs/controller-runtime/pull/99/files — The UID comparison  is still correct in most cases, maybe we can revisit although would like to understand a bit more what problem we're trying to solve first.

**Comment by therealak12** [comment]
Not a serious problem actually. I just wanted my code to be consistent in comparing references. I use this `IsControlledBy` and also the internal function of controller-runtime for checking controller and non-controller owner references.
