### ISSUE TITLE
How to use proxy with `NewUpgradeRequestRoundTripper`?

### ISSUE THREAD

**Issue by jwcesign** [kubernetes/apimachinery#161]
As https://github.com/kubernetes/kubernetes/issues/120318 said, kubectl didn't suport proxy with `proxy-url`.

I check the code and, the reason is function `NewUpgradeRequestRoundTripper `, but how to use NewUpgradeRequestRoundTripper with `proxy-url`?

Is there any one could help me?

Thanks a lot~

**Comment by ardaguclu** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/120318;
/close
