### ISSUE TITLE
no DeepCopyObject() method for watch.Event type

### ISSUE THREAD

**Issue by fatih** [kubernetes/apimachinery#18]
Hi,

We're using the `watch.Event` type in our internal code base extensively. Some of the places encode it as well. After upgrading to latest client-go it stopped compiling because of the missing method `DeepCopyObject`. Seems like the following line is missing (https://github.com/kubernetes/apimachinery/blob/master/pkg/watch/watch.go#L54):

```
// k8s:deepcopy-gen:interfaces=k8s.io/kubernetes/runtime.Object
```

Can we generate this method for this type as well? I can open a PR but wasn't sure if that was intentionally like this.

**Comment by deads2k** [comment]
@sttts

**Comment by sttts** [comment]
@fatih please take a look at https://github.com/kubernetes/client-go/issues/259. Sounds like the same problem, i.e. vendoring of the wrong apimachinery version.

**Comment by fatih** [comment]
@sttts Thanks for the info. But we're using now the latest apimachinery and I think this type should have this method anyway as it might be needed (we do now). Is there a way we could add these ?

**Comment by sttts** [comment]
@fatih got it. I am hestitant to turn `watch.Event` into an object. It is an internal type not meant to be serialized. It misses the `GetObjectKind() schema.ObjectKind` implementation as well. Why don't you use `metav1.WatchEvent`?

**Comment by fatih** [comment]
@sttts sure, but seems like it's not the same struct. It expects a `runtime.RawExtension`, not a `runtime.Object`. 

>  It is an internal type not meant to be serialized

I'm using it for testing a `Watch()` call from the client. An example from the test I use:

```
ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		panic("need flusher!")
	}

	w.Header().Set("Transfer-Encoding", "chunked")
	w.WriteHeader(http.StatusOK)
	flusher.Flush()

	scheme := runtime.NewScheme()
	jsonSerializer := kubejson.NewSerializer(
		kubejson.DefaultMetaFactory, scheme, scheme, false)

	encoder := streaming.NewEncoder(w, jsonSerializer)
        // this is the place where it doesn't work anymore as `watch.Event()` doesn't have DeepCopyBoject() anymore
	if err := encoder.Encode(watch.Event{
		Type:   watch.Added,
		Object: obj,
	},
	); err != nil {
		panic(err)
	}

	flusher.Flush()
}))
defer ts.Close()

config := &rest.Config{
	Host: ts.URL,
}

client, err := NewClient(config)
if err != nil {
	t.Fatal(err)
}

// Certificates is a TPR we have implemented internally, but same logic applies to other resources
watcher, err := client.Certificates("default").Watch(metav1.ListOptions{})
if err != nil {
	t.Fatal(err)
}

ch := watcher.ResultChan()
event, ok := <-ch
if !ok {
	t.Errorf("should get a response, didn't have anything")
}
```

If there is any other solutions I'm happy to test it, but adding the `DeepObjectObject()` at least is useful for reasons like this (testing).

**Comment by sttts** [comment]
Compare vendor/k8s.io/apiserver/pkg/endpoints/handlers/watch.go:221. That's the http watch server in kube. It converts the `watch.Event` to a `metav1.Event` by essentially writing the embedded `runtime.Object` into the `RawExtension`'s `Object` field (in `Convert_versioned_InternalEvent_to_versioned_Event`). Then the encoder will do the serialization normally.

**Comment by fatih** [comment]
Thanks @sttts.

**Comment by fatih** [comment]
@sttts Sure, thanks for the help again.
