### ISSUE TITLE
Did someone push a rogue tag?

### ISSUE THREAD

**Issue by porthorian** [kubernetes/apimachinery#180]
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/8bd0f310-c28f-45bf-8652-91c223cc44ea">

https://github.com/kubernetes/apimachinery/compare/v0.30.2...v0.30.3

**Comment by dims** [comment]
@porthorian an automated bot generates tags in this repo based on staging directories in the main kubernetes repo, so you can cross verify if there are changes there.
- https://github.com/kubernetes/kubernetes/tree/master/staging#external-repository-staging-area
- https://github.com/kubernetes/apimachinery/commits/release-1.30
