### ISSUE TITLE
Need another sync 

### ISSUE THREAD

**Issue by mikebrow** [kubernetes/apimachinery#22]
The following commit in kubernetes is now blocking our ability to move up to fixes we (kubernetes-incubator/cri-containerd) need in kubernetes:

https://github.com/kubernetes/kubernetes/commit/1b3836d5df302281a9db4b03bdc8fd5079142431

Specifically the above commit moved "List" from "k8s.io/api/types.go" to the following location in their staging version of apimachinery "k8s.io/apimachinery/pkg/apis/meta/internalversion/types.go"

@Random-Liu

**Comment by caesarxuchao** [comment]
The publishing robot has been down for weeks. @sttts is working on a fix. We will push a round of manual syncs.

**Comment by mikebrow** [comment]
Publishing robot issue discussion and temporary manual resolution WIP: 
https://github.com/kubernetes/kubernetes/issues/51643

**Comment by mikebrow** [comment]
Issue resolved temporarily by linking to branches from https://github.com/sttts

**Comment by sttts** [comment]
All repos are pushed. This can be closed.
