### ISSUE TITLE
Ship a Gopkg.toml

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/apimachinery#23]
...to help `dep` users get the correct version of dependencies (e.g., k8s.io/apimachinery).

**Comment by sttts** [comment]
To avoid duplicated work, I have prototype code for the publishing bot to do this when a release tag from the kube repo is converted into one of the published repo. Obviously, the Gopkg.toml should not reference sha1 revisions, but tags, for client-go preferably the semver tag.

**Comment by lavalamp** [comment]
Yeah, maybe I filed this in the wrong place.

**Comment by nikhita** [comment]
We have go.mod now, so closing. :)
