### ISSUE TITLE
People (sttts, caesarxuchao) need to be able to stage api-machinery code

### ISSUE THREAD

**Issue by fejta** [kubernetes/apimachinery#24]
Assigning to @kubernetes/sig-api-machinery-misc leads:
/assign @deads2k @lavalamp 

Please give @sttts @caesarxuchao write access to the following repos:

- [ ] k8s.io/code-generator
- [ ] k8s.io/sample-apiserver
- [ ] k8s.io/kube-aggregator
- [ ] k8s.io/apiserver
- [ ] k8s.io/client-go
- [ ] k8s.io/api master
- [ ] k8s.io/apimachinery
- [ ] k8s.io/metrics
- [ ] k8s.io/apiextensions-apiserver

This is basically a repetition of kubernetes/kubernetes#51643, the same situation 2 weeks ago.

Status Quo: The github publisher bot https://github.com/kubernetes/test-infra/tree/master/mungegithub/publisher is not pushing the repos right now because it cannot cope with a number of commits (merges) and branch structures (fast-forward master merges) and falls over. Fixes are being reviewed #4134, but it might take another 1-2 weeks until they are ready and maybe more days to build up the confidence again that we can let it push nightly automatically.

To unblock people with components depending on 1.8 another soon'ish push is necessary. For that the bot is run in a private GKE cluster now and pushes to private forks (https://github.com/sttts/client-go, https://github.com/sttts/apiserver, ...). The actual manual push is a sequence of fast-forward pushes. These are codified in

https://gist.github.com/anonymous/2fd6e66e9364dd87e66b12cdb9bd92dc for the pushes, all fast-forward (no force-pushes!)
https://gist.github.com/anonymous/62e661ea6dde3cb7615023f2e7fd69fb for the latest repo heads for a possible roll-back.
Only somebody with push permissions to the repos can execute them. Neither I nor @caesarxuchao have these permisssions. PRs against the repos do not work either because they linearize the branches and destroy the structure we need to consistently create tags.

What we need:

somebody to give us (@sttts and @caesarxuchao) push permissions (or some special user for that we have access to) for those repos to do this push and maybe some more until the bot is running again.
As the situation can happen easily again that the bot falls over (or even pushes wrong content such that we have to react reasonably fast), I would feel much better with (2). Last time it took 3.5 days until we were able to do (1) after asking a number of people for help, not a good experience.

/cc @kubernetes/sig-api-machinery-misc @fejta @lavalamp @thockin @wojtek-t @smarterclayton @eparis

Further context: kubernetes/kubernetes#51643 https://github.com/kubernetes/test-infra/issues/4499

**Comment by eparis** [comment]
Humans having this access and doing this by hand feels totally wrong. This needs to be automated by the infrastructure. We already have some humans who can do hacky things, but I don't think that's what we need for a maintainable future...

**Comment by lavalamp** [comment]
I agree w/ @eparis, I will try to sync up w/ @fejta in a higher bandwidth
medium to avoid going back and forth on this.

**Comment by lavalamp** [comment]
Let's take this back to the other issue.

**Comment by sttts** [comment]
> Humans having this access and doing this by hand feels totally wrong. This needs to be automated by the infrastructure. We already have some humans who can do hacky things, but I don't think that's what we need for a maintainable future...

I cannot follow. We are working hard to get the bot into a shape again that we can run it automatically. To unblock people until this is the case, we need a workaround. That's what this is about. Honestly, this comment feels like a punch into the face. It's tedious and frustrating to run after people with the mercy to do the updates on my and @caesarxuchao's behalf. I spent quite a number of days fixing infrastructure I and many people rely on, but is broken for 6 weeks. And for the last 7 days this is an awful experience in the project, pushback and ignorance instead of encouragement and support.
