### ISSUE TITLE
Bazel BUILD files are broken

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/apimachinery#30]
e.g. [This](https://github.com/kubernetes/apimachinery/blob/18a564baac720819100827c16fdebcadb05b2d0d/pkg/util/sets/BUILD#L44) label points to a dependency that is not vendored.

**Comment by mattmoor** [comment]
I am trying to consume this library to put together a sample CRD / Controller in Go for rules_k8s, but this is blocking my ability to pull in this library. :(

**Comment by mattmoor** [comment]
@ixdy FYI

**Comment by ixdy** [comment]
This is probably an issue with the publisher (https://github.com/kubernetes/test-infra/tree/master/mungegithub/publisher) not understanding bazel.

@caesarxuchao is the publisher still maintained? if so, who owns it these days?

**Comment by caesarxuchao** [comment]
afaik, publisher hasn't been running for months. @sttts manually published the changes a few times.

**Comment by mattmoor** [comment]
Could we add something that gates pushes on `bazel {build,test} ...`?  Maybe a little `.travis.yml` on these repos?

**Comment by mattmoor** [comment]
it looks to me like the `Godeps` are out of date for this directory, which is probably the source of things.  What is responsible for testing these weird `Godeps` directories floating in the middle of the K8s tree?

**Comment by ixdy** [comment]
cc @justinsb 

What is the process for publishing the staging/ changes to destination repos? Is there a script or program that's run that I can extend?

**Comment by mattmoor** [comment]
Looking with fresh eyes, this isn't a vendoring problem because this is a reference to `k8si.io/apimachinery`, it should have it's prefix truncated because it is pointing to its own subdirectory.  Simply dropping `vendor/k8s.io/apimachinery` should be sufficient.

**Comment by mattmoor** [comment]
I saw this, but not sure if it is what you want: https://github.com/kubernetes/apimachinery/blob/master/hack/sync-from-kubernetes.sh.

**Comment by mattmoor** [comment]
This one has one too: https://github.com/kubernetes/sample-apiserver/blob/master/hack/sync-from-kubernetes.sh

I don't see them in k/k

**Comment by mattmoor** [comment]
I also don't see their friend `godep-deps.sh` in k/k.

**Comment by mattmoor** [comment]
It looks like the logic to update Godeps doesn't take into account cross-dependencies between `k8s.io/foo`.  Forking and fixing `apimachinery`, I see that there is still a dependency on `k8s.io/code-generator`, which isn't vendored :(

**Comment by sttts** [comment]
@mattmoor The bot does not support BUILD files and leaves them untouched. We can prune them if that help. Wdyt?

k8s.io/code-generator is not vendored. We discussed that yesterday in Slack briefly. We should fix that for 1.9, either by getting godep to include it somehow (with artificial imports?) or by tweaking the bot.

@ixdy this is the bot as it is running for weeks against github.com/sttts: https://github.com/kubernetes/test-infra/pull/4134. We did a couple of manual cross-repo pushes from github.com/sttts to github.com/kubernetes and will do probably do the next one as soon as 1.9.0-beta1 is tagged. After code-freeze I plan to resume the work on the bot. It has to run nightly again aginst the real repos. I would be happy to include you and @mattmoor into the review process if you are interested. We have to move this topic onto more shoulders than myself and @caesarxuchao.

**Comment by mattmoor** [comment]
Can we create symlinks from `//vendor/k8s.io/apimachinery/` to the root of the staging repo?

Otherwise, it is a simple `sed` command to rewrite the `BUILD` files:
```shell
sed -i 's@vendor/k8s.io/apimachinery/@@g' $(find -name BUILD)'
```

**Comment by mattmoor** [comment]
To color this with a bit more context for @sttts and @caesarxuchao (since @ixdy knows my master plan)....

I am trying to put together samples in `bazelbuild/rules_k8s` for how to build a controller (eventually apiserver) in Go with Bazel, and deploy it with those rules (perhaps eventually `sample-apiserver` too, but cart before horse).

The goal is to enable folks to do for Controller / APIServer development what I recently demoed at Bazelcon for Prow: 4 second dev cycle to rebuild / repush / redeploy.

I used this when I was building the [WarmImage CRD](https://github.com/mattmoor/warm-image), and it was very nice, but currently I only have Python fleshed out.  I'd like to land Go next.

**Comment by caesarxuchao** [comment]
@sttts is there an issue tracking why we don't include k8s.io/code-generator is not vendored?

**Comment by sttts** [comment]
> @sttts is there an issue or doc tracking why we don't include k8s.io/code-generator is not vendored?

Now there is: https://github.com/kubernetes/kubernetes/issues/55967

**Comment by caesarxuchao** [comment]
@mattmoor sorry I'm still learning bazel. Is bazel supposed to re-generate the `k8s.io/apimachinery/pkg/util/set` on each build? Can bazel just use the existing go files without regenerating the cdoe? I mean the `set` package is quite trivial, it doesn't justify to vendor the code-generator into apimachinery.

**Comment by ash2k** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/37598

**Comment by sttts** [comment]
BUILD files are stripped from the staging repos on export for quite some time. Closing.
