### ISSUE TITLE
labels.Set.AsSelector and labels.SelectorFromSet ignore errors and select everything in that case

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/apimachinery#31]
It should return also error, not hide it and return selector matching everything. We used [.AsSelector](
https://github.com/kubernetes/apimachinery/blob/a0c9892b4fdd2632ded0da92ef8c2d5326b6c734/pkg/labels/labels.go#L61) in our reaper which ended up deleting everything because of it. Sure, it was unvalidated input (selector value was "_aaaa") but not returning an error and ignoring it is a bug. Pretty sure this is widely used and error prone.

https://github.com/kubernetes/apimachinery/blob/a0c9892b4fdd2632ded0da92ef8c2d5326b6c734/pkg/labels/selector.go#L803

**Comment by tnozicka** [comment]
@sttts ideas who to ping about this?

**Comment by sttts** [comment]
@tnozicka have you followed the dependencies? Is it feasible to add the error there? I feel like the error handling (and possibly ignoring it) should be done at the call sites, not in the helper.

**Comment by tnozicka** [comment]
> I feel like the error handling (and possibly ignoring it) should be done at the call sites, not in the helper.

+1

I haven't followed the dependencies but the error has to be propagated either way. No matter the count. In the worst can you can always specifically ignore it on call sites where it would be hard to propagate while doing the change.

**Comment by sttts** [comment]
Is this still the case?

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/89747, we now simply construct the Selector without any validation, which means that the server will just reject the request if any of the requirements is invalid.

/close
