### ISSUE TITLE
Pluralize name algorithm is different in apimachinery and gengo

### ISSUE THREAD

**Issue by mixj93** [kubernetes/apimachinery#40]
Comparing [apimachinery/pkg/api/meta/restmapper.go](https://github.com/kubernetes/apimachinery/blob/0ed326127d3068118ef128c76673dad6005736ba/pkg/api/meta/restmapper.go#L160) and [gengo/blob/master/namer/plural_namer.go](https://github.com/kubernetes/gengo/blob/01a732e01d00cb9a81bb0ca050d3e6d2b947927b/namer/plural_namer.go#L65), I find that apimachinery and gengo have a different algorithm of pluralize name, it's fine at most time, but it becomes tricky when the name ends with capital 'S'.

In apimachinery add "es" will pass the test:
```
{Kind: "MongoRS", Plural: "mongorses", Singular: "mongors"}
```

But in gengo add 's' will pass the test:
```
{
    "MongoRS",
    "mongorss",
    "MongoRSs",
},
```

It seems that in apimachinery, `ToLower()` first and then add 'es' after lowercase 's', but in gengo add 's' after Capital 'S' first then `ToLower()`.

the package `k8s.io/gengo/namer` was used in `k8s.io/code-generator` and I use it to generate CRD client and it's different from apimachinery generated rest api.

Maybe apimachinery may use funcs in gengo to stay the same.

**Comment by tamalsaha** [comment]
I took a shot at exposing AddSpecific() method via `RESTMapper` interface. This affects both `apimachinery` and `client-go` repo. This is what it looks like in 1.10:
https://github.com/kubedb/apimachinery/pull/225/commits/4adee2376b9259376c4b7a6e71acb8c6029d86f0

This allowed me to call `AddSpecific` later: https://github.com/kubedb/apimachinery/blob/740a349d583dd4b4ce2b4c4caffa55979e2d6228/hack/gencrd/main.go#L57

Please guide what will be future proof way to resolve this.

**Comment by deads2k** [comment]
> Deleting UnsafeGuessKindToResource sounds like a great idea but I don't see how. Do you think AddSpecific method be added to RESTMapper interface ?

No.  Take a look at master.  There's no static RESTMapper anymore since the RESTMapping cannot be done without access to a server and isn't valuable without a server.  Since it's all pulled from discovery, the server is authoritative.

**Comment by tamalsaha** [comment]
Pardon my ignorance, but I am still not understanding how plural and singular resource names are generated for aggregate api server types. For CRDs, I understand that it is coming from users when CRD is registered with api server.

I looked at commit https://github.com/kubernetes/apimachinery/commit/e8bbda8703883049fd61224db26596a7af2fbd71 .

**Comment by liggitt** [comment]
> I am still not understanding how plural and singular resource names are generated for aggregate api server types.

That is up to the aggregated server. It serves its own discovery documents at the group/version level

**Comment by tamalsaha** [comment]
@liggitt , understood. Can you please point me how that is done in master branch? I am familiar with codepath when the announced package was still around. 

What I really want is that this issue be resolved in 1.11 release one way or other (I don't have an opinion on how).

**Comment by tamalsaha** [comment]
After digging through the sample-apiserver code, I understand how this is working in master. Basically for EAS, the plural form is coming from `apiGroupInfo.VersionedResourcesStorageMap` and later [used](https://github.com/kubernetes/apiserver/blob/a2affdf2c58bd3d026a6832908b0e2f5ca8960fa/pkg/endpoints/installer.go#L100) to respond to discovery request. So, this pluralization issue should be fixed in master. 

Thanks!

**Comment by lavalamp** [comment]
As for me, I would like to delete the plural namer from gengo, it should not have a plural namer. I am sure there was a good reason it was written but that's not generally applicable code.

**Comment by lavalamp** [comment]
Also I think "mongorse" is going to be my new favorite nonsense-resource-name :)

**Comment by deads2k** [comment]
> Also I think "mongorse" is going to be my new favorite nonsense-resource-name :)

Hang on.  I think that our standard naming is based on foreign fishes created by random word generators.... :)

**Comment by fyuan1316** [comment]
The same problem was encountered. Is there any progress on this issue?

**Comment by lavalamp** [comment]
Do not use this code. A human should somehow enter or declare the pluralized form.
