### ISSUE TITLE
"(sw *StreamWatcher) receive()" receive io.EOF  every 30~50 minittues?

### ISSUE THREAD

**Issue by zhangcunli** [kubernetes/apimachinery#41]
I use client-go to watch k8s service and endpoints like this:
clientset.CoreV1().Services("").Watch(metav1.ListOptions{})

But every 30~50 minittues，the StreamWatcher will receive the io.EOF.
"(sw *StreamWatcher) receive()" receive io.EOF and stop.  
And I have to watch again.

**Comment by liggitt** [comment]
It is normal for the apiserver to timeout watch requests and for clients to have to reestablish them

**Comment by zhangcunli** [comment]
@liggitt 
Thanks! 
So I have to re-watch when apiserver timeout?

**Comment by liggitt** [comment]
yes. the helpers built on top of StreamWatcher (cache.Informer, which uses ListerWatcher) do this for you, and call add/update/delete handlers you specify

see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/workqueue/main.go#L164-L195 as an example
