### ISSUE TITLE
Bash for Windows: fatal error: runtime: netpoll failed (syscall)

### ISSUE THREAD

**Issue by bjornmagnusson** [kubernetes/apimachinery#42]
When running Helm 2.9.0-rcX in Bash for Windows, the entire application crashes.
This version of Helm was the first with support for K8S 1.10.
Below error does not appear in Helm 2.8.x or earlier.
Got advice from Helm core maintainer in https://github.com/kubernetes/helm/issues/3833 to report it here.

runtime: epollwait on fd 7 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x1619830, 0x17)
/usr/local/go/src/runtime/panic.go:616 +0x81
runtime.netpoll(0x5d207926fc500, 0xc400000000)
/usr/local/go/src/runtime/netpoll_epoll.go:75 +0x216
runtime.sysmon()
/usr/local/go/src/runtime/proc.go:4265 +0x424
runtime.mstart1(0x0)
/usr/local/go/src/runtime/proc.go:1227 +0xe7
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1193 +0x76

goroutine 1 [runnable, locked to thread]:
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName(0xc420320c40, 0x1614fc4, 0x14, 0x1600cac, 0x2, 0x12c31f7, 0xd, 0x17486a0, 0xc4203218c0)
/go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:199 +0x498
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0xc420320c40, 0x1614fc4, 0x14, 0x1600cac, 0x2, 0xc4204dc7b0, 0x4, 0x4)
/go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:167 +0x168
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion(0xc420320c40, 0x1614fc4, 0x14, 0x1600cac, 0x2)
/go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/register.go:50 +0x39d
k8s.io/helm/vendor/k8s.io/api/authorization/v1.addKnownTypes(0xc420320c40, 0x0, 0x0)
/go/src/k8s.io/helm/vendor/k8s.io/api/authorization/v1/register.go:53 +0x1a6
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme(0x20a9d70, 0xc420320c40, 0x0, 0x0)
/go/src/k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime/scheme_builder.go:29 +0x6d
k8s.io/helm/vendor/k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme-fm(0xc420320c40, 0x0, 0x0)
/go/src/k8s.io/helm/vendor/k8s.io/api/core/v1/register.go:41 +0x34
k8s.io/helm/vendor/k8s.io/client-go/kubernetes/scheme.AddToScheme(0xc420320c40)
/go/src/k8s.io/helm/vendor/k8s.io/client-go/kubernetes/scheme/register.go:87 +0xc9
k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/scheme.init.0()
/go/src/k8s.io/helm/vendor/k8s.io/kubernetes/pkg/kubectl/scheme/install.go:60 +0x85

goroutine 5 [chan receive]:
k8s.io/helm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x20abb40)
/go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by k8s.io/helm/vendor/github.com/golang/glog.init.0
/go/src/k8s.io/helm/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

**Comment by amandadebler** [comment]
I get pretty much the exact same result with v2.9.1 in Ubuntu for WSL, even when running "helm --help"
