### ISSUE TITLE
metav1.ListOptions LabelSelector field takes string instead of LabelSelector{} object

### ISSUE THREAD

**Issue by timfallmk** [kubernetes/apimachinery#47]
I'm not sure I'm framing this issue correctly, but I'm trying to pass multiple `LabelSelector`s to the `metav1.ListOptions` construct (currently I have them as a `map[string]string`), but the `LabelSelector` on that struct only takes a string.

https://github.com/kubernetes/apimachinery/blob/594fc14b6f143d963ea2c8132e09e73fe244b6c9/pkg/apis/meta/v1/types.go#L321-L324

Are multiple selectors intended to be passed as a single concatenated string? Is it even possible to specify multiple selectors for `ListOptions`? I found a possibly related conversion function, but I'm not sure that covers the correct case.

https://github.com/kubernetes/apimachinery/blob/594fc14b6f143d963ea2c8132e09e73fe244b6c9/pkg/apis/meta/v1/conversion.go#L279-L293

Apologies if this ended up in the wrong place. The reference is vapor-ware/ksync#216 if that helps.

**Comment by liggitt** [comment]
The string is the serialized form you would pass as a query parameter. It can be parsed into a selector using https://github.com/kubernetes/apimachinery/blob/master/pkg/labels/selector.go#L799

**Comment by timfallmk** [comment]
@liggitt I figured, but I asking if it's the serialized form of a _single_ selector, or _multiple_ (comma separated?) selectors. I can pass a single selector key, value pair in without issue.

**Comment by liggitt** [comment]
It accepts the multi value form as well

**Comment by timfallmk** [comment]
Helpful to document as a side note.

**Comment by alcheagle** [comment]
From the usage perspective is there any way to obtain that string from a `var labels map[string]`? I would prefer not to write this function by myself. 

As a side note please add this into the `k8s.io/apimachinery/pkg/apis/meta/v1.ListOptions.LabelSelector` documentation, as it is not clear.

**Comment by liggitt** [comment]
> is there any way to obtain that string from a var labels map[string]string

See https://godoc.org/k8s.io/apimachinery/pkg/labels#Set

```go
import "k8s.io/apimachinery/pkg/labels"

map := map[string]string{...}
labels.Set(map).String()
```

**Comment by alcheagle** [comment]
Thank you for your help

**Comment by vimalk78** [comment]
> It accepts the multi value form as well (`a=x,b=y`) as well as complex forms (`a IN (x,y,z)`)

I get this error if i use with the form `a IN (x,y,z)` : 
`Error listing pods unable to parse requirement: found 'IN', expected: '=', '!=', '==', 'in', notin'`

perhaps a casing issue. works with `in`

**Comment by ghostsquad** [comment]
I would also like to have more/better documentation for constructing a label selector as a string. 

ExternalDNS allows filtering on annotations and uses

```
metav1.ParseToLabelSelector(
```

https://github.com/kubernetes-sigs/external-dns/commit/16194ca9cfe2bf43730f15b7d0ecf48816633ebc?ts=4#diff-dbc7c67b1209bdd63ba26a2bcdbfe69dR163

But unfortunately they don't provide much documentation besides the simple single filter `X=Y`

**Comment by ghostsquad** [comment]
this page definitely helps:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
