### ISSUE TITLE
Generating type with openapi-gen that includes Quantity, does not succeed to generate entry for infDecAmount

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/apimachinery#48]
I have some type that looks like 
```
type EmptyDiskSource struct {
	// Capacity of the sparse disk.
	Capacity resource.Quantity `json:"capacity"`
}
```
when I run `openapi-gen` on it, I have 
```
"kubevirt.io/kubevirt/pkg/api/v1.EmptyDiskSource": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "EmptyDisk represents a temporary disk which shares the vmis lifecycle.",
					Properties: map[string]spec.Schema{
						"capacity": {
							SchemaProps: spec.SchemaProps{
								Description: "Capacity of the sparse disk.",
								Ref:         ref("k8s.io/apimachinery/pkg/api/resource.Quantity"),
							},
						},
					},
					Required: []string{"capacity"},
				},
			},
			Dependencies: []string{
				"k8s.io/apimachinery/pkg/api/resource.Quantity"},
		},
...
"k8s.io/apimachinery/pkg/api/resource.Quantity": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and Int64() accessors.\n\nThe serialization format is:\n\n<quantity>        ::= <signedNumber><suffix>\n  (Note that <suffix> may be empty, from the \"\" case in <decimalSI>.)\n<digit>           ::= 0 | 1 | ... | 9 <digits>          ::= <digit> | <digit><digits> <number>          ::= <digits> | <digits>.<digits> | <digits>. | .<digits> <sign>            ::= \"+\" | \"-\" <signedNumber>    ::= <number> | <sign><number> <suffix>          ::= <binarySI> | <decimalExponent> | <decimalSI> <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei\n  (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)\n<decimalSI>       ::= m | \"\" | k | M | G | T | P | E\n  (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)\n<decimalExponent> ::= \"e\" <signedNumber> | \"E\" <signedNumber>\n\nNo matter which of the three exponent forms is used, no quantity may represent a number greater than 2^63-1 in magnitude, nor may it have more than 3 decimal places. Numbers larger or more precise will be capped or rounded up. (E.g.: 0.1m will rounded up to 1m.) This may be extended in the future if we require larger or smaller quantities.\n\nWhen a Quantity is parsed from a string, it will remember the type of suffix it had, and will use the same type again when it is serialized.\n\nBefore serializing, Quantity will be put in \"canonical form\". This means that Exponent/suffix will be adjusted up or down (with a corresponding increase or decrease in Mantissa) such that:\n  a. No precision is lost\n  b. No fractional digits will be emitted\n  c. The exponent (or suffix) is as large as possible.\nThe sign will be omitted unless the number is negative.\n\nExamples:\n  1.5 will be serialized as \"1500m\"\n  1.5Gi will be serialized as \"1536Mi\"\n\nNOTE: We reserve the right to amend this canonical format, perhaps to\n  allow 1.5 to be canonical.\n  or after March 2015.\n\nNote that the quantity will NEVER be internally represented by a floating point number. That is the whole point of this exercise.\n\nNon-canonical values will still parse as long as they are well formed, but will be re-emitted in their canonical form. (So always use canonical form, or don't diff.)\n\nThis format is intended to make it difficult to use these numbers without writing some sort of special handling code in the hopes that that will cause implementors to also use a fixed point implementation.",
					Properties: map[string]spec.Schema{
						"i": {
							SchemaProps: spec.SchemaProps{
								Description: "i is the quantity in int64 scaled form, if d.Dec == nil",
								Ref:         ref("k8s.io/apimachinery/pkg/api/resource.int64Amount"),
							},
						},
						"d": {
							SchemaProps: spec.SchemaProps{
								Description: "d is the quantity in inf.Dec form if d.Dec != nil",
								Ref:         ref("k8s.io/apimachinery/pkg/api/resource.infDecAmount"),
							},
						},
						"s": {
							SchemaProps: spec.SchemaProps{
								Description: "s is the generated value of this quantity to avoid recalculation",
								Type:        []string{"string"},
								Format:      "",
							},
						},
						"Format": {
							SchemaProps: spec.SchemaProps{
								Description: "Change Format at will. See the comment for Canonicalize for more details.",
								Type:        []string{"string"},
								Format:      "",
							},
						},
					},
					Required: []string{"i", "d", "s", "Format"},
				},
			},
			Dependencies: []string{
				"k8s.io/apimachinery/pkg/api/resource.infDecAmount", "k8s.io/apimachinery/pkg/api/resource.int64Amount"},
		},
...
"k8s.io/apimachinery/pkg/api/resource.int64Amount": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "int64Amount represents a fixed precision numerator and arbitrary scale exponent. It is faster than operations on inf.Dec for values that can be represented as int64.",
					Properties: map[string]spec.Schema{
						"value": {
							SchemaProps: spec.SchemaProps{
								Type:   []string{"integer"},
								Format: "int64",
							},
						},
						"scale": {
							SchemaProps: spec.SchemaProps{
								Type:   []string{"integer"},
								Format: "int32",
							},
						},
					},
					Required: []string{"value", "scale"},
				},
			},
			Dependencies: []string{},
		},
...
```
but I do not have entry for `k8s.io/apimachinery/pkg/api/resource.infDecAmount`, I think it because that `infDecAmount` type includes type from go standard library and they can not be auto-generated by `openapi-gen`. I can set `// +k8s:openapi-gen=false` on problematic field
```
// d is the quantity in inf.Dec form if d.Dec != nil
// +k8s:openapi-gen=false
d infDecAmount
```
,  but I do not sure if it good solution.

**Comment by liggitt** [comment]
that's odd... you shouldn't get all of those internal fields... they are not part of the wire-format and are not exposed externally.

you should get something like this:

`"io.k8s.apimachinery.pkg.api.resource.Quantity": {
    "description": "Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and Int64() accessors.\n\nThe serialization format is:\n\n\u003cquantity\u003e        ::= \u003csignedNumber\u003e\u003csuffix\u003e\n  (Note that \u003csuffix\u003e may be empty, from the \"\" case in \u003cdecimalSI\u003e.)\n\u003cdigit\u003e           ::= 0 | 1 | ... | 9 \u003cdigits\u003e          ::= \u003cdigit\u003e | \u003cdigit\u003e\u003cdigits\u003e \u003cnumber\u003e          ::= \u003cdigits\u003e | \u003cdigits\u003e.\u003cdigits\u003e | \u003cdigits\u003e. | .\u003cdigits\u003e \u003csign\u003e            ::= \"+\" | \"-\" \u003csignedNumber\u003e    ::= \u003cnumber\u003e | \u003csign\u003e\u003cnumber\u003e \u003csuffix\u003e          ::= \u003cbinarySI\u003e | \u003cdecimalExponent\u003e | \u003cdecimalSI\u003e \u003cbinarySI\u003e        ::= Ki | Mi | Gi | Ti | Pi | Ei\n  (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)\n\u003cdecimalSI\u003e       ::= m | \"\" | k | M | G | T | P | E\n  (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)\n\u003cdecimalExponent\u003e ::= \"e\" \u003csignedNumber\u003e | \"E\" \u003csignedNumber\u003e\n\nNo matter which of the three exponent forms is used, no quantity may represent a number greater than 2^63-1 in magnitude, nor may it have more than 3 decimal places. Numbers larger or more precise will be capped or rounded up. (E.g.: 0.1m will rounded up to 1m.) This may be extended in the future if we require larger or smaller quantities.\n\nWhen a Quantity is parsed from a string, it will remember the type of suffix it had, and will use the same type again when it is serialized.\n\nBefore serializing, Quantity will be put in \"canonical form\". This means that Exponent/suffix will be adjusted up or down (with a corresponding increase or decrease in Mantissa) such that:\n  a. No precision is lost\n  b. No fractional digits will be emitted\n  c. The exponent (or suffix) is as large as possible.\nThe sign will be omitted unless the number is negative.\n\nExamples:\n  1.5 will be serialized as \"1500m\"\n  1.5Gi will be serialized as \"1536Mi\"\n\nNote that the quantity will NEVER be internally represented by a floating point number. That is the whole point of this exercise.\n\nNon-canonical values will still parse as long as they are well formed, but will be re-emitted in their canonical form. (So always use canonical form, or don't diff.)\n\nThis format is intended to make it difficult to use these numbers without writing some sort of special handling code in the hopes that that will cause implementors to also use a fixed point implementation.",
    "type": "string"
   },
`

**Comment by liggitt** [comment]
what version of openapi-gen are you using?

**Comment by cynepco3hahue** [comment]
> you should get something like this:

Just to be sure do you talk about `func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition` inside `openapi_generated.go` file, because I can see it includes only a single function.

I used branch release-1.9 to install it, maybe it really the reason, will try some recent branch.

**Comment by cynepco3hahue** [comment]
Indeed, version was the source of the problem, after changing the branch from `release-1.9` to `release-1.10`, `resource.Quantity` looks much better:
```
		"k8s.io/apimachinery/pkg/api/resource.Quantity": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Type:   resource.Quantity{}.OpenAPISchemaType(),
					Format: resource.Quantity{}.OpenAPISchemaFormat(),
				},
			},
		}
```
I close the issue, @liggitt thx for help.
