### ISSUE TITLE
Kubernetes initializer IncludeUninitialized parameter is deprecated how can my initializer controller list and watch for uninitialized objects now?

### ISSUE THREAD

**Issue by xiaoxiadazhi** [kubernetes/apimachinery#60]
In the latest version of kubernetes/apimachinery，the includeUninitialized parameter is deprecated，how can my initializer controller list and watch for uninitialized objects now?
Thanks!

**Comment by xiaoxiadazhi** [comment]
I want to develop a initializer，and use client-go modify depolement ,but there are many errors.





# cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1beta1
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:39:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:44:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:49:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:54:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:59:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:64:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGe
neratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1beta1\zz_generated.conversion.go:69:13: s.AddConversionFunc undefined (type *runtime.Scheme has no field or method AddConversionF
unc)
# cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:39:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:44:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:49:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:54:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:59:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:64:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:69:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
vendor\k8s.io\client-go\pkg\apis\clientauthentication\v1alpha1\zz_generated.conversion.go:74:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddG
eneratedConversionFunc)
# cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:67:3: undefined: v1.Convert_Map_string_To_string_To_v1_LabelSelector
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:68:3: undefined: v1.Convert_v1_LabelSelector_To_Map_string_To_string
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:83:4: undefined: v1.CreateOptions
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:84:4: undefined: v1.UpdateOptions
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:101:4: undefined: v1.CreateOptions
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\register.go:102:4: undefined: v1.UpdateOptions
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\zz_generated.conversion.go:38:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGenerat
edConversionFunc)
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\zz_generated.conversion.go:43:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGenerat
edConversionFunc)
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\zz_generated.conversion.go:48:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGenerat
edConversionFunc)
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\zz_generated.conversion.go:53:13: s.AddGeneratedConversionFunc undefined (type *runtime.Scheme has no field or method AddGenerat
edConversionFunc)
vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion\zz_generated.conversion.go:53:13: too many errors
# cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/client-go/kubernetes/scheme
vendor\k8s.io\client-go\kubernetes\scheme\register.go:70:27: cannot use "k8s.io/api/auditregistration/v1alpha1".AddToScheme (type func(*"k8s.io/apimachinery/pkg/runtime".Scheme) error)
as type func(*"cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/apimachinery/pkg/runtime".Scheme) error in array or slice literal
vendor\k8s.io\client-go\kubernetes\scheme\register.go:77:20: cannot use v2beta2.AddToScheme (type func(*"k8s.io/apimachinery/pkg/runtime".Scheme) error) as type func(*"cloud.tencent.com
/tke/flexvolume-xfs-quota/vendor/k8s.io/apimachinery/pkg/runtime".Scheme) error in array or slice literal
vendor\k8s.io\client-go\kubernetes\scheme\register.go:117:2: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/apimachinery/pkg/util/runtime".Must

D:\GOPATH\src\cloud.tencent.com\tke\flexvolume-xfs-quota>go build initializer/xfs_quota-initializer.go
# cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/client-go/kubernetes/typed/storage/v1
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:40:10: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:41:10: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:42:16: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:45:48: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:46:34: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachmentList
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:48:87: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:65:82: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:77:68: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachmentList
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:107:54: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:118:54: undefined: "cloud.tencent.com/tke/flexvolume-xfs-quota/vendor/k8s.io/api/storage/v1".VolumeAttachment
vendor\k8s.io\client-go\kubernetes\typed\storage\v1\volumeattachment.go:118:54: too many errors

**Comment by liggitt** [comment]
The alpha initializer feature is removed in 1.14, see https://groups.google.com/forum/m/#!topic/kubernetes-dev/6gO_CxEOn5s

Because it was an alpha feature, there is no deprecation period for the feature and it is being removed over a single release boundary, per https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

/close
