### ISSUE TITLE
Unused dependency github.com/ghodss/yaml listed in go module

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/apimachinery#64]
I'm currently relying on `k8s.io/apimachinery/pkg/apis/meta/v1` package in a Go project, as well as `sigs.k8s.io/yaml`.

However, it seems like `k8s.io/apimachinery/pkg/apis/meta/v1.test` is using `github.com/ghodss/yaml` instead:

```
go mod why github.com/ghodss/yaml
# github.com/ghodss/yaml
<<my project>>
k8s.io/apimachinery/pkg/apis/meta/v1
k8s.io/apimachinery/pkg/apis/meta/v1.test
github.com/ghodss/yaml
```

When I look at the code (https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/apimachinery%24+ghodss) I only see the package listed in go.mod and Godeps.json, but it's actually not used in *.go files:

```
Godeps/Godeps.json
46:			"ImportPath": "github.com/ghodss/yaml",

pkg/api/meta/OWNERS
27:- ghodss

go.sum
17:github.com/ghodss/yaml v0.0.0-20150909031657-73d445a93680 h1:ZktWZesgun21uEDrwW7iEV1zPCGQldM2atlJZ3TdvVM=
18:github.com/ghodss/yaml v0.0.0-20150909031657-73d445a93680/go.mod h1:4dBDuWmgqj2HViK6kFavaiC9ZROes6MMH2rRYeMEF04=
```

**Comment by ahmetb** [comment]
For some reason I'm unable to get `go mod tidy` to remove it from `go.sum`.

When I delete it manually, it keeps coming back when I run `go mod tidy`.

**Comment by liggitt** [comment]
what version of `k8s.io/apimachinery` are you using?

**Comment by ahmetb** [comment]
Good point. I was on `k8s.io/apimachinery v0.0.0-20180528140728-94ebb086c69b` now I bumped to `k8s.io/apimachinery v0.0.0-20190717022731-0bb8574e0887` and the problem went away.

I'll close this, but it might be good to remove the unused reference from Godeps.json, I'm feeling like `go mod` is reading that to add it back to go.sum.

**Comment by liggitt** [comment]
`go mod` doesn't look at Godeps.json

$ GO111MODULE=on go mod graph | grep ghodss
k8s.io/kube-openapi@v0.0.0-20190709113604-33be087ad058 github.com/ghodss/yaml@v0.0.0-20150909031657-73d445a93680

that's why it's still getting pulled into the sum file

**Comment by dims** [comment]
fyi, we are working on trying to removing `ghodss/yaml` https://github.com/kubernetes/kubernetes/issues/77024
