### ISSUE TITLE
ObjectMeta.CreationTimestamp should be a pointer?

### ISSUE THREAD

**Issue by itaysk** [kubernetes/apimachinery#68]
`ObjectMeta.CreationTimestamp`'s json tag says `omitempty`, but it's a struct so as far as I understand it can never satisfy the "empty" check (zero value or nil). 
https://github.com/kubernetes/apimachinery/blob/master//pkg/apis/meta/v1/types.go#L199

Every other field in `ObjectMeta` is of type that can be zero or nil (slices and primitives). Also, we can take example from `ObjectMeta.DeletionTimestamp` which is a pointer to struct.

**Comment by liggitt** [comment]
it's desired, but unclear how to do compatibly.

tracked in https://github.com/kubernetes/kubernetes/issues/67610 (just reopened)

/close
