### ISSUE TITLE
Need Version and Revision details for Release 1.10.0-beta.2

### ISSUE THREAD

**Issue by sunnyanand17** [kubernetes/apimachinery#69]
Hi Team,

Can someone pls share the version and revision details that can be used in the go.mod file for Release 1.10.0-beta.2?

**Comment by liggitt** [comment]
tags corresponding to kubernetes releases did not get added until ~1.12 era

the https://github.com/kubernetes/apimachinery/tree/release-1.10 branch corresponds to HEAD of the kubernetes release-1.10 branch

v1.10.0-beta.2 was SHA 63dad40a0391b7af32c34fdbf41fa199c3b247ad on  Wed Mar 7 20:28:36 2018

Looking at this repo, that corresponds to https://github.com/kubernetes/apimachinery/commit/30e1d93fbac3539695e7010ae06c93029a001e67
