### ISSUE TITLE
StreamWatcher memory leak

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/apimachinery#70]
We are using the StreamWatcher and seeing extremely high memory allocations. Attached is a memory profile:

[pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz](https://github.com/kubernetes/apimachinery/files/3535312/pprof.pilot-discovery.alloc_objects.alloc_space.inuse_objects.inuse_space.033.pb.gz)

From this we have 9.6 GB of memory allocated by the StreamWatcher.

To get to this state I had a deployment with 200 replicas, and every 30 seconds I redeployed all of the pods (`kubectl rollout restart`). I left this running overnight and saw this memory usage.

**Comment by kensipe** [comment]
@howardjohn issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
could you resubmit there?

**Comment by vikramk7** [comment]
> @howardjohn issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
> could you resubmit there?

Submitted  https://github.com/kubernetes/kubernetes/issues/91686.

**Comment by liggitt** [comment]
thanks, tracking in https://github.com/kubernetes/kubernetes/issues/91686

/close
