### ISSUE TITLE
Would be useful to have a AddLabels() in the meta API

### ISSUE THREAD

**Issue by champak** [kubernetes/apimachinery#73]
Hi, In using the meta info API I had needed to add my own labels. I had to do a get, add labels to what got retrieved and then use the SetLabels() api. Any reason why we do not have a "AddLabels()" api with the semantics of adding onto the labels map ? I am assuming this must have come up before but could not locate an applicable thread. Thanks.

**Comment by liggitt** [comment]
A smaller API surface area of simple getters/setters is preferred, and allows building helper methods like AddLabels/RemoveLabels on top

/close

**Comment by champak** [comment]
Thanks for responding. IMHO Add/Remove labels seems basic enough to be part of the base API but a minimal API surface does have its advantages..
