### ISSUE TITLE
No retry to connect back if connection fails

### ISSUE THREAD

**Issue by chlete** [kubernetes/apimachinery#74]
Hi,

In the following function:

https://github.com/kubernetes/apimachinery/blob/6c8691705fc5427b8f3866dafc1ee47c1cd8f081/pkg/util/proxy/upgradeaware.go#L416

There's no retry to connect back after a failure. Not sure if should be handled here though. However my proposal is to use an exponential backoff retry (https://godoc.org/github.com/cenkalti/backoff).

If it should be handled here, please let me know, and I will be happy to supply a PR.

Regards,
Christian

**Comment by liggitt** [comment]
I would not expect a single request to the frontend to result in multiple connections/requests by the backend

**Comment by chlete** [comment]
Thanks for the feedback @liggitt. You are right, I made the wrong assumption. It's not needed here at all.
