### ISSUE TITLE
DeepEqual and Quantity

### ISSUE THREAD

**Issue by JeremyMarshall** [kubernetes/apimachinery#75]
We had a strange bug with kubebuilder 2.0 and Quantity.

We are building ResourceQuotas and comparing them to the existing. Sometimes, they do not compare correctly (false change) as we do 
```
requestsCPU, _  := resource.ParseQuantity(resourceQuota.Requests.CPU)
```
type operations to build the desired state. 
if the code 
```
default:
    if scale%3 == 0 && !strings.HasSuffix(shifted, "000") && shifted[0] != '0' {
        return Quantity{i: int64Amount{value: result, scale: Scale(scale)}, Format: format, s: str}, nil
    }
}
```
is triggered, e.g. changing the scale, then DeepEqual will fail as attribute `s` will be set, but not in the one from kube as that will already be converted.

There is a fix to rebuild the quotas before comparing them but it is a gotcha
```
.
.
.
cq := make(map[corev1.ResourceName]string,6)
for k, v := range foundResourceQuota.Spec.Hard { 
    cq[k] = v.String()
}
if !reflect.DeepEqual(rq, cq) {
.
.
.
```
https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go#L324

**Comment by liggitt** [comment]
reflect.DeepEqual will not return true for semantically equal quantity objects. That is the purpose of the semantic equality DeepEqual method (apiequality.Semantic.DeepEqual, see https://godoc.org/k8s.io/apimachinery/pkg/api/equality)

**Comment by JeremyMarshall** [comment]
@liggitt Thats very nice. I'm not sure how we fell into `reflect.DeepEqual` 

Certainly kubebuilder 1.0 mentions it https://book-v1.book.kubebuilder.io/basics/simple_controller.html.

I'll close it and link it to kubebuilder
