### ISSUE TITLE
RESTMapper Pluralization Logic Is Too Limited

### ISSUE THREAD

**Issue by irishshagua** [kubernetes/apimachinery#77]
The pluralization logic (here)[https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/restmapper.go#L141] caused us issues with a custom resource definition that we were testing. The resource name that we were using was a `FabricGateway` which when pluralized should have been `FabricGateways`, however it was incorrectly being pluralized as `FabricGatewaies`.

**Comment by kensipe** [comment]
@irishshagua issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
could you resubmit there?

**Comment by irishshagua** [comment]
> @irishshagua issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
> could you resubmit there?

Ok, issue created:
https://github.com/kubernetes/kubernetes/issues/89034
