### ISSUE TITLE
Use log levels that match SIG Instrumentation logging conventions

### ISSUE THREAD

**Issue by jodavis-suse** [kubernetes/apimachinery#82]
There are a few lines of selector.go [0] which use klog.V(10).  The sig-instrumentation established convention [1] is to use Info values from 0 to 5.  
As part of this issue, it is worth reviewing all the log lines to verify they follow the intended conventions for log levels based on the severity of the message.

[0] https://github.com/kubernetes/apimachinery/blob/f30c0235171023905e0c3cf646c7f16409384495/pkg/labels/selector.go#L220
[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by kensipe** [comment]
@jodavis-suse issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
could you resubmit there?

**Comment by jodavis-suse** [comment]
Can do.
I filed a sibling issue in https://github.com/kubernetes/kubernetes/issues/87867 for client-go, though that got a lot of pushback.  I'm not yet clear if the right approach is to make the changes to log levels as this issue and 87867 do, or if the Logging Conventions should be clarified for scope and intent and this change abandoned.

**Comment by jodavis-suse** [comment]
OK, we can close this issue in favor of https://github.com/kubernetes/kubernetes/issues/89020

If you have any thoughts on the issue, please comment there.
