### ISSUE TITLE
Question/Potential Feature: Or Field Selector

### ISSUE THREAD

**Issue by abbasally5** [kubernetes/apimachinery#84]
is there any reason kubernetes does not have an Or fieldSelector? It currently contains an And fieldSelector. This is the relevant file: https://github.com/kubernetes/apimachinery/blob/master/pkg/fields/selector.go

If not, I would be happy to implement it (or atleast try).

**Comment by lavalamp** [comment]
/sig api-machinery

I vaguely recall this being deliberate and having something to do with the reverse lookup.

Permitting an OR clause would make it possible to express e.g. 3SAT problems as a label selector, making it impossible in the general case to determine if it is possible for any set of labels to match. I can imagine that being important for some systems, but I'm not sure if it's important for ours.
