### ISSUE TITLE
RFC3339Micro requires precision that the spec does not seem to require.

### ISSUE THREAD

**Issue by technosophos** [kubernetes/apimachinery#88]
The Go `time.RFC3339Nano` format is `2006-01-02T15:04:05.999999999Z07:00`, while the meta/v1 apimachinery package has  the `RFC3339Micro` format set to `2006-01-02T15:04:05.000000Z07:00` (Note the zeros instead of nines).

https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/micro_time.go#L26

A parse error results when a client sends a date that does not use placeholder zeros to right-pad the microseconds. E.g. the timestamp `2006-01-02T15:04:05.1234Z07:00` will cause a parse error because the microtime is not right-padded.

Since (a) this is inconsistent with Go's interpretation of RFC3339, and (b) a parser ought to opt for leniency when strictness does not improve the fidelity or integrity of the data, it seems that the date format used in `micro_time.go` might best be changed to use `9` instead of `0`.

**Comment by kensipe** [comment]
@technosophos issues for api-machinery are managed https://github.com/kubernetes/kubernetes/issues
could you resubmit there?

**Comment by technosophos** [comment]
Done. https://github.com/kubernetes/kubernetes/issues/89156
