### ISSUE TITLE
NewDocumentDecoder fails with bufio.Scanner: token too long

### ISSUE THREAD

**Issue by kensipe** [kubernetes/apimachinery#89]
When calling `NewDocumentDecoder` the token size for the buffer is the default which is NOT changable. Larger documents (which is likely when using a yaml separator) cause a `bufio.Scanner: token too long`

This was uncovered using kudo... the issue is https://github.com/kudobuilder/kudo/issues/1397

The fixing PR https://github.com/kudobuilder/kudo/pull/1400 provides more detail if needed.

This was against api-machinery 0.16.6

Code concern is: https://github.com/kubernetes/apimachinery/blob/release-1.6/pkg/util/yaml/decoder.go#L94

**Comment by kensipe** [comment]
cc: @lavalamp   This should probably be in the main repo

**Comment by kensipe** [comment]
moved Issue to proper issue list ^^

**Comment by lavalamp** [comment]
Thanks, sorry! I opened https://github.com/kubernetes/kubernetes/issues/89015
