### ISSUE TITLE
Unexpected behaviour of YAML decoder

### ISSUE THREAD

**Issue by glyn** [kubernetes/apimachinery#91]
I tried using the API machinery YAML utility to split a stream of YAML documents into individual documents. It doesn’t seem to cope with certain cases and I am wondering if that was intentional, a restriction, or what.

In particular, directives don't appear to be grouped with the document they apply to. For example:
```
%YAML 1.2
---
a: b
...
%YAML 1.2
---
c: d
```

splits into three documents instead of two:
```
%YAML 1.2
```
```
a: b
...
%YAML 1.2
```
```
c: d
```

See the code here which reproduces the above: https://play.golang.org/p/fgqRm_16LJV.

There are also small issues around when newlines are preserved.

Ideally, `NewDocumentDecoder` should satisfy these properties:
* each document produced should be a valid YAML document consisting of a substring of the input string
* when the documents produced are concatenated together, the resultant string should be equal to the input string

Here is some code and a test which pins down the unexpected behaviour a bit better: [split.go.txt](https://github.com/kubernetes/apimachinery/files/4419616/split.go.txt),[split_test.go.txt](https://github.com/kubernetes/apimachinery/files/4419617/split_test.go.txt). (I added the `.txt` to the filenames since I couldn't attach `.go` files.)

**Comment by dims** [comment]
fyi https://github.com/kubernetes/kubernetes/issues/34146

also this repo is not really watched as this is bot generated/updated repo. please use kubernetes/kubernetes

**Comment by glyn** [comment]
> fyi [kubernetes/kubernetes#34146](https://github.com/kubernetes/kubernetes/issues/34146)

That's pretty revealing. Thanks.

> 
> also this repo is not really watched as this is bot generated/updated repo. please use kubernetes/kubernetes

Moved to https://github.com/kubernetes/kubernetes/issues/89764
