### ISSUE TITLE
Help convert `resource.Quantity` to a `float64`

### ISSUE THREAD

**Issue by zlesnr** [kubernetes/apimachinery#93]
Hello.  I'm seeing that floats are not supported in https://github.com/kubernetes-sigs/controller-tools/issues/245.  In that case, how is one meant to convert from a `resource.Quantity` to a `float64`?  I've got an operator that needs to make call out to an API that requires a `float64`, but it seems that the tools I'm meant to use here require the spec make use of a `resource.Quantity`.  Please help.

**Comment by louyiping** [comment]
Hi. Do you have any idea now ?

**Comment by zlesnr** [comment]
I used a string instead @louyiping.  Then `strings.ParseFlaot()` to help.

**Comment by louyiping** [comment]
This also works. Thanks. @zlesnr
