### ISSUE TITLE
wrong value when getting Quantity giga scale value

### ISSUE THREAD

**Issue by alfredcai** [kubernetes/apimachinery#99]
```go
import (
	kres "k8s.io/apimachinery/pkg/api/resource"
)

func main() {
	quantity, _ := kres.ParseQuantity("2Gi")
	println(quantity.ScaledValue(kres.Giga))
	println(quantity.ScaledValue(kres.Mega))
	println(quantity.Value())
	println(quantity.String())
}
```
the result is wrong when getting a giga scale. 
```
3
2148
2147483648
2Gi
```

**Comment by liggitt** [comment]
Gi is the binary unit (1073741824 bytes)

ScaledValue returns decimal scale (`ScaledValue returns the value of ceil(q / 10^scale).`), so ceil(2*1073741824 / 10^3) = 3

"2G" would construct a decimal quantity that would return 2 for ScaledValue(3)

/close
